/* parse.js — turns an uploaded PDF into candidate transactions.

   Column position parsing turned out to be unreliable on real bank PDFs:
   a column's header label and the data underneath it are often not at the
   same x position (padding differs), so trusting header x as a column
   boundary silently misfiles data into the wrong column.

   Instead, each line on the page is read by *content shape*:
     - a date-shaped token
     - amount-shaped tokens (currency numbers)
     - everything else = description text
   A line that has both a date and at least one amount starts a new
   transaction; the LAST amount on that line is always the running closing
   balance (right-most column), and the balance's change from the previous
   transaction's balance tells us debit vs credit — this sidesteps needing
   to know exactly where the "Withdrawal" vs "Deposit" columns sit at all.
   Lines with only description text are wrapped continuation lines.

   Scanned (image) pages fall back to on-device OCR before parsing text. */
const Parse = (() => {

  if (window.pdfjsLib) {
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
  }

  const TESS_OPTS = {
    workerPath: 'https://cdn.jsdelivr.net/npm/tesseract.js@5.0.5/dist/worker.min.js',
    corePath: 'https://cdn.jsdelivr.net/npm/tesseract.js-core@5.0.0/tesseract-core.wasm.js',
    langPath: 'https://tessdata.projectnaptha.com/4.0.0',
  };

  let dateFormat = localStorage.getItem('ledger-date-format') || 'DMY';
  function setDateFormat(fmt) { dateFormat = fmt; localStorage.setItem('ledger-date-format', fmt); }
  function getDateFormat() { return dateFormat; }

  const MONTHS = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
  function fullYear(y) { return y.length === 2 ? 2000 + parseInt(y) : parseInt(y); }
  function isoDate(year, month, day) {
    if (!year || !month || !day || month < 1 || month > 12 || day < 1 || day > 31) return null;
    return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
  }
  function normalizeDate(raw, yearHint) {
    const s = raw.trim().replace(/,/g, '');
    let m = s.match(/^(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{2,4}))?$/);
    if (m) {
      let [, a, b, y] = m;
      let year = y ? fullYear(y) : yearHint;
      let n1 = parseInt(a), n2 = parseInt(b);
      let month, day;
      if (dateFormat === 'MDY') { month = n1; day = n2; } else { day = n1; month = n2; }
      if (month > 12 && day <= 12) { [month, day] = [day, month]; }
      return isoDate(year, month, day);
    }
    m = s.match(/^([A-Za-z]{3,9})\.?\s+(\d{1,2})\s*(\d{2,4})?$/);
    if (m) { const mi = MONTHS.indexOf(m[1].slice(0,3).toLowerCase()); if (mi >= 0) return isoDate(m[3] ? fullYear(m[3]) : yearHint, mi + 1, parseInt(m[2])); }
    m = s.match(/^(\d{1,2})\s+([A-Za-z]{3,9})\.?\s*(\d{2,4})?$/);
    if (m) { const mi = MONTHS.indexOf(m[2].slice(0,3).toLowerCase()); if (mi >= 0) return isoDate(m[3] ? fullYear(m[3]) : yearHint, mi + 1, parseInt(m[1])); }
    return null;
  }

  function parseAmount(raw) {
    let s = (raw || '').trim();
    let negative = false;
    if (s.startsWith('(') && s.endsWith(')')) { negative = true; s = s.slice(1, -1); }
    if (s.startsWith('-')) { negative = true; s = s.slice(1); }
    s = s.replace(/[₹$€£,\s]/g, '');
    const value = parseFloat(s);
    return { value: isNaN(value) ? null : value, negative };
  }

  const DATE_TOKEN = /^\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}$/;
  const AMOUNT_TOKEN = /^\(?-?[₹$€£]?\d[\d,]*\.\d{1,2}\)?$/;
  const REF_NUMBER_TOKEN = /^\d{9,}$/;
  const INCOME_HINTS = /DEPOSIT|PAYROLL|SALARY|DIRECT\s*DEP|CREDIT\s*(?!CARD)|REFUND|REIMBURSEMENT|INTEREST\s*PAID|TRANSFER\s*IN|PAYMENT\s*RECEIVED|NEFT\s*CR|IB\s*FUNDS\s*TRANSFER\s*CR|ACH\s*C-/i;
  const FOOTER_NOISE = /^(HDFC BANK|state account branch|registered office|contents of this statement|closing balance includes|statement summary|opening balance|generated on|generated by|requesting branch|this is a computer|not require signature|page no|nomination|statement of account|account branch|account type|account status|account no|a\/c open|rtgs|ifsc|branch code|joint holders|cust id|od limit|currency|phone no|email|from\s*:|to\s*:|dr count|cr count|debits|credits|closing bal)/i;

  function isHeaderLine(text) {
    return /narration|description|particulars/i.test(text) && /withdrawal|deposit|debit|credit/i.test(text) && /date/i.test(text);
  }

  /* ---------------- page → lines (grouped by visual row) ---------------- */

  async function getLines(page) {
    const content = await page.getTextContent();
    const items = content.items
      .map(it => ({ str: it.str, x: it.transform[4], y: it.transform[5] }))
      .filter(it => it.str.trim().length > 0);
    const buckets = new Map();
    for (const it of items) {
      const key = Math.round(it.y / 2.5);
      if (!buckets.has(key)) buckets.set(key, []);
      buckets.get(key).push(it);
    }
    return [...buckets.entries()]
      .sort((a, b) => b[0] - a[0])
      .map(([, its]) => its.sort((a, b) => a.x - b.x));
  }

  /* ---------------- content-pattern transaction extraction ---------------- */

  function extractTransactionsFromLines(lines, yearHint) {
    const out = [];
    let current = null;
    let lastBalance = null;

    function finalize() {
      if (!current) return;
      const amounts = current.amounts;
      const date = normalizeDate(current.date, yearHint);
      const desc = current.narration.replace(/\s+/g, ' ').trim();
      current = null;
      if (!date || amounts.length === 0 || desc.length < 2) return;

      const balance = amounts[amounts.length - 1];
      let magnitude = amounts.length >= 2 ? amounts[amounts.length - 2] : null;
      let isIncome = null;

      if (lastBalance !== null) {
        const delta = +(balance - lastBalance).toFixed(2);
        if (Math.abs(delta) > 0.005) {
          isIncome = delta > 0;
          if (magnitude === null || Math.abs(Math.abs(delta) - magnitude) > 1) magnitude = Math.abs(delta);
        }
      }
      if (isIncome === null) isIncome = INCOME_HINTS.test(desc);
      lastBalance = balance;

      if (magnitude && magnitude > 0) out.push({ date, description: desc, amount: magnitude, isIncome });
    }

    for (const line of lines) {
      const lineText = line.map(it => it.str).join(' ').trim();
      if (!lineText) continue;
      if (isHeaderLine(lineText) || FOOTER_NOISE.test(lineText)) { finalize(); continue; }

      const dateTokens = [];
      const amountTokens = [];
      const textParts = [];
      for (const it of line) {
        const s = it.str.trim();
        if (!s) continue;
        if (DATE_TOKEN.test(s)) { dateTokens.push(s); continue; }
        if (AMOUNT_TOKEN.test(s)) { const { value } = parseAmount(s); if (value !== null) amountTokens.push({ x: it.x, v: value }); continue; }
        if (REF_NUMBER_TOKEN.test(s)) continue;
        textParts.push(s);
      }
      amountTokens.sort((a, b) => a.x - b.x);

      if (dateTokens.length > 0 && amountTokens.length > 0) {
        finalize();
        current = { date: dateTokens[0], narration: textParts.join(' '), amounts: amountTokens.map(a => a.v) };
      } else if (current && textParts.length) {
        current.narration += ' ' + textParts.join(' ');
      }
    }
    finalize();
    return out;
  }

  /* ---------------- generic single-line fallback (non-tabular statements) ---------------- */

  const DATE_RE = '(\\d{1,2}[\\/\\-]\\d{1,2}(?:[\\/\\-]\\d{2,4})?|[A-Za-z]{3,9}\\.?\\s+\\d{1,2}(?:,?\\s*\\d{2,4})?|\\d{1,2}\\s+[A-Za-z]{3,9}\\.?(?:\\s*\\d{2,4})?)';
  const AMOUNT_RE = '(\\(?-?[₹$]?\\d[\\d,]*\\.\\d{1,2}\\)?)\\s*(CR|DR)?';
  const LINE_RE = new RegExp('^\\s*' + DATE_RE + '\\s+(.+?)\\s+' + AMOUNT_RE + '\\s*$', 'i');

  function extractLineCandidates(text, yearHint) {
    const lines = text.split(/\r?\n/);
    const out = [];
    for (const rawLine of lines) {
      const line = rawLine.replace(/\s+/g, ' ').trim();
      if (line.length < 6 || FOOTER_NOISE.test(line)) continue;
      const m = line.match(LINE_RE);
      if (!m) continue;
      const [, dateRaw, descRaw, amountRaw, crdr] = m;
      const date = normalizeDate(dateRaw, yearHint);
      const { value, negative } = parseAmount(amountRaw);
      if (!date || value === null || value === 0) continue;
      let desc = descRaw.trim();
      if (desc.length < 2 || /^(balance|total|subtotal|page \d|statement period|summary)/i.test(desc)) continue;
      let isIncome = negative ? false : (INCOME_HINTS.test(desc) || crdr === 'CR');
      if (crdr === 'DR' || negative) isIncome = false;
      out.push({ date, description: desc, amount: Math.abs(value), isIncome });
    }
    return out;
  }

  /* ---------------- OCR fallback for scanned pages ---------------- */

  let ocrWorkerPromise = null;
  async function getOcrWorker() {
    if (!ocrWorkerPromise) ocrWorkerPromise = Tesseract.createWorker('eng', 1, TESS_OPTS);
    return ocrWorkerPromise;
  }
  async function ocrCanvas(canvas) {
    const worker = await getOcrWorker();
    const { data } = await worker.recognize(canvas);
    return data.text || '';
  }

  /* ---------------- debug helper ---------------- */

  async function debugExtract(file) {
    const buf = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({ data: buf, password: undefined });
    loadingTask.onPassword = (updatePassword, reason) => {
      const isRetry = reason === pdfjsLib.PasswordResponses.INCORRECT_PASSWORD;
      const pwd = window.prompt(isRetry ? 'That password didn\u2019t work. Try again:' : 'This statement is password protected. Enter its password:');
      if (pwd === null) { loadingTask.destroy(); return; }
      updatePassword(pwd);
    };
    const pdf = await loadingTask.promise;
    const yearHint = new Date().getFullYear();
    let allLines = [];
    for (let i = 1; i <= Math.min(pdf.numPages, 3); i++) {
      const page = await pdf.getPage(i);
      allLines = allLines.concat(await getLines(page));
    }
    const candidates = extractTransactionsFromLines(allLines, yearHint);
    return {
      pageCount: pdf.numPages,
      lineCount: allLines.length,
      firstLinesSample: allLines.slice(0, 20).map(l => l.map(it => it.str).join(' | ')),
      candidateCount: candidates.length,
      candidateSample: candidates.slice(0, 8),
    };
  }

  /* ---------------- main entry point ---------------- */

  async function parseStatement(file, onStatus) {
    const buf = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({ data: buf, password: undefined });
    loadingTask.onPassword = (updatePassword, reason) => {
      const isRetry = reason === pdfjsLib.PasswordResponses.INCORRECT_PASSWORD;
      const pwd = window.prompt(isRetry ? 'That password didn\u2019t work. Try again:' : 'This statement is password protected. Enter its password:');
      if (pwd === null) { loadingTask.destroy(); return; }
      updatePassword(pwd);
    };
    const pdf = await loadingTask.promise;
    const yearHint = new Date().getFullYear();

    const pages = [];
    let charCount = 0;
    for (let i = 1; i <= pdf.numPages; i++) {
      onStatus && onStatus(`Reading page ${i} of ${pdf.numPages}…`);
      const page = await pdf.getPage(i);
      const content = await page.getTextContent();
      const pageText = content.items.map(it => it.str).join('\n');
      charCount += pageText.trim().length;
      pages.push({ page, pageText });
    }

    const isScanned = (charCount / pdf.numPages) < 40;

    if (isScanned) {
      let fullText = '';
      for (let i = 0; i < pages.length; i++) {
        onStatus && onStatus(`Running on-device OCR, page ${i + 1} of ${pages.length}…`);
        const { page } = pages[i];
        const viewport = page.getViewport({ scale: 2.2 });
        const canvas = document.createElement('canvas');
        canvas.width = viewport.width; canvas.height = viewport.height;
        await page.render({ canvasContext: canvas.getContext('2d'), viewport }).promise;
        fullText += (await ocrCanvas(canvas)) + '\n';
      }
      return extractLineCandidates(fullText, yearHint);
    }

    onStatus && onStatus('Reading transaction table…');
    let allLines = [];
    for (const { page } of pages) allLines = allLines.concat(await getLines(page));
    const tableCandidates = extractTransactionsFromLines(allLines, yearHint);
    if (tableCandidates.length > 0) return tableCandidates;

    const fullText = pages.map(p => p.pageText).join('\n');
    return extractLineCandidates(fullText, yearHint);
  }

  return { parseStatement, extractLineCandidates, normalizeDate, parseAmount, setDateFormat, getDateFormat, debugExtract };
})();
