/* parse.js — turns an uploaded PDF into candidate transactions.
   Strategy, in order:
   1. Positional table parser — reconstructs rows/columns from each word's
      position on the page. This is what real bank statement tables need,
      since a table's "Withdrawal" and "Deposit" columns and wrapped
      descriptions don't come out as one clean line of text.
   2. Generic single-line regex parser — fallback for simpler statements
      where date, description and one amount sit on the same line.
   Scanned (image) pages fall back to on-device OCR before either parser runs. */
const Parse = (() => {

  if (window.pdfjsLib) {
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
  }

  const TESS_OPTS = {
    workerPath: 'https://cdn.jsdelivr.net/npm/tesseract.js@5.0.5/dist/worker.min.js',
    corePath: 'https://cdn.jsdelivr.net/npm/tesseract.js-core@5.0.0/tesseract-core.wasm.js',
    langPath: 'https://tessdata.projectnaptha.com/4.0.0',
  };

  // ---- date order setting (India/UK statements are DD/MM; US statements are MM/DD) ----
  let dateFormat = localStorage.getItem('ledger-date-format') || 'DMY';
  function setDateFormat(fmt) { dateFormat = fmt; localStorage.setItem('ledger-date-format', fmt); }
  function getDateFormat() { return dateFormat; }

  const MONTHS = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];

  function fullYear(y) { return y.length === 2 ? 2000 + parseInt(y) : parseInt(y); }
  function isoDate(year, month, day) {
    if (!year || !month || !day || month < 1 || month > 12 || day < 1 || day > 31) return null;
    return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
  }

  function normalizeDate(raw, yearHint) {
    const s = raw.trim().replace(/,/g, '');
    let m = s.match(/^(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{2,4}))?$/);
    if (m) {
      let [, a, b, y] = m;
      let year = y ? fullYear(y) : yearHint;
      let n1 = parseInt(a), n2 = parseInt(b);
      let month, day;
      if (dateFormat === 'MDY') { month = n1; day = n2; } else { day = n1; month = n2; }
      // safety: if the chosen order is impossible (e.g. "13" as a month), swap
      if (month > 12 && day <= 12) { [month, day] = [day, month]; }
      return isoDate(year, month, day);
    }
    m = s.match(/^([A-Za-z]{3,9})\.?\s+(\d{1,2})\s*(\d{2,4})?$/);
    if (m) {
      const mi = MONTHS.indexOf(m[1].slice(0,3).toLowerCase());
      if (mi >= 0) return isoDate(m[3] ? fullYear(m[3]) : yearHint, mi + 1, parseInt(m[2]));
    }
    m = s.match(/^(\d{1,2})\s+([A-Za-z]{3,9})\.?\s*(\d{2,4})?$/);
    if (m) {
      const mi = MONTHS.indexOf(m[2].slice(0,3).toLowerCase());
      if (mi >= 0) return isoDate(m[3] ? fullYear(m[3]) : yearHint, mi + 1, parseInt(m[1]));
    }
    return null;
  }

  function parseAmount(raw) {
    let s = (raw || '').trim();
    let negative = false;
    if (s.startsWith('(') && s.endsWith(')')) { negative = true; s = s.slice(1, -1); }
    if (s.startsWith('-')) { negative = true; s = s.slice(1); }
    s = s.replace(/[₹$€£,\s]/g, '');
    const value = parseFloat(s);
    return { value: isNaN(value) ? null : value, negative };
  }

  const AMOUNT_TOKEN = /^\(?-?[₹$€£]?\d[\d,]*\.\d{1,2}\)?$/;
  const DATE_TOKEN = /^\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}$/;

  /* ---------------- STRATEGY 1: positional table parser ---------------- */

  const HEADER_PATTERNS = {
    date:      /^date$/i,
    narration: /narration|description|particulars|details/i,
    chqRef:    /chq|ref\.?no/i,
    valueDt:   /value\s*dt|value\s*date/i,
    withdrawal:/withdrawal|debit/i,
    deposit:   /deposit|credit/i,
    balance:   /balance/i,
  };

  const FOOTER_NOISE = /^(HDFC BANK|state account branch|registered office|contents of this statement|closing balance includes|statement summary|opening balance|generated on|generated by|requesting branch|this is a computer|not require signature|page no|nomination|statement of account|account branch|account type|account status|account no|a\/c open|rtgs|ifsc|branch code|joint holders|cust id|od limit|currency|phone no|email|from\s*:|to\s*:)/i;

  async function getLines(page) {
    const content = await page.getTextContent();
    const items = content.items
      .map(it => ({ str: it.str, x: it.transform[4], y: it.transform[5] }))
      .filter(it => it.str.trim().length > 0);
    const buckets = new Map();
    for (const it of items) {
      const key = Math.round(it.y / 2.5);
      if (!buckets.has(key)) buckets.set(key, []);
      buckets.get(key).push(it);
    }
    return [...buckets.entries()]
      .sort((a, b) => b[0] - a[0])
      .map(([, its]) => its.sort((a, b) => a.x - b.x));
  }

  function findHeader(lines) {
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const found = {};
      for (const it of line) {
        for (const [col, pattern] of Object.entries(HEADER_PATTERNS)) {
          if (!found[col] && pattern.test(it.str.trim())) found[col] = it.x;
        }
      }
      if (found.date !== undefined && found.narration !== undefined &&
          (found.withdrawal !== undefined || found.deposit !== undefined)) {
        return { rowIndex: i, columns: found };
      }
    }
    return null;
  }

  function columnAt(x, sortedCols) {
    let best = sortedCols[0].name;
    for (const c of sortedCols) {
      if (x >= c.x - 4) best = c.name; else break;
    }
    return best;
  }

  async function extractTableFromPage(page, yearHint) {
    const lines = await getLines(page);
    const header = findHeader(lines);
    if (!header) return [];

    const sortedCols = Object.entries(header.columns)
      .map(([name, x]) => ({ name, x }))
      .sort((a, b) => a.x - b.x);

    const rows = [];
    let current = null;

    for (let i = header.rowIndex + 1; i < lines.length; i++) {
      const line = lines[i];
      const lineText = line.map(it => it.str).join(' ').trim();
      if (FOOTER_NOISE.test(lineText)) { if (current) rows.push(current); current = null; continue; }

      const cells = { date: '', narration: '', withdrawal: '', deposit: '', balance: '' };
      for (const it of line) {
        const col = columnAt(it.x, sortedCols);
        if (cells[col] !== undefined) cells[col] += (cells[col] ? ' ' : '') + it.str;
      }

      const looksLikeNewRow = DATE_TOKEN.test(cells.date.trim());
      if (looksLikeNewRow) {
        if (current) rows.push(current);
        current = { date: cells.date.trim(), narration: cells.narration.trim(), withdrawal: cells.withdrawal.trim(), deposit: cells.deposit.trim() };
      } else if (current) {
        // continuation line — only narration text, no amounts of its own
        const extra = cells.narration.trim();
        if (extra) current.narration += ' ' + extra;
      }
    }
    if (current) rows.push(current);

    const out = [];
    for (const r of rows) {
      const date = normalizeDate(r.date, yearHint);
      if (!date) continue;
      const w = parseAmount(r.withdrawal);
      const d = parseAmount(r.deposit);
      let amount = null, isIncome = false;
      if (d.value && d.value > 0) { amount = d.value; isIncome = true; }
      else if (w.value && w.value > 0) { amount = w.value; isIncome = false; }
      if (amount === null) continue;
      let desc = r.narration.replace(/\s+/g, ' ').trim();
      if (desc.length < 2) continue;
      out.push({ date, description: desc, amount, isIncome });
    }
    return out;
  }

  /* ---------------- STRATEGY 2: generic single-line parser ---------------- */

  const DATE_RE = '(\\d{1,2}[\\/\\-]\\d{1,2}(?:[\\/\\-]\\d{2,4})?|[A-Za-z]{3,9}\\.?\\s+\\d{1,2}(?:,?\\s*\\d{2,4})?|\\d{1,2}\\s+[A-Za-z]{3,9}\\.?(?:\\s*\\d{2,4})?)';
  const AMOUNT_RE = '(\\(?-?[₹$]?\\d[\\d,]*\\.\\d{1,2}\\)?)\\s*(CR|DR)?';
  const LINE_RE = new RegExp('^\\s*' + DATE_RE + '\\s+(.+?)\\s+' + AMOUNT_RE + '\\s*$', 'i');
  const INCOME_HINTS = /DEPOSIT|PAYROLL|SALARY|DIRECT\s*DEP|CREDIT\s*(?!CARD)|REFUND|REIMBURSEMENT|INTEREST\s*PAID|TRANSFER\s*IN|PAYMENT\s*RECEIVED/i;

  function extractLineCandidates(text, yearHint) {
    const lines = text.split(/\r?\n/);
    const out = [];
    for (const rawLine of lines) {
      const line = rawLine.replace(/\s+/g, ' ').trim();
      if (line.length < 6 || FOOTER_NOISE.test(line)) continue;
      const m = line.match(LINE_RE);
      if (!m) continue;
      const [, dateRaw, descRaw, amountRaw, crdr] = m;
      const date = normalizeDate(dateRaw, yearHint);
      const { value, negative } = parseAmount(amountRaw);
      if (!date || value === null || value === 0) continue;
      let desc = descRaw.trim();
      if (desc.length < 2 || /^(balance|total|subtotal|page \d|statement period|summary)/i.test(desc)) continue;
      let isIncome = negative ? false : (INCOME_HINTS.test(desc) || crdr === 'CR');
      if (crdr === 'DR' || negative) isIncome = false;
      out.push({ date, description: desc, amount: Math.abs(value), isIncome });
    }
    return out;
  }

  /* ---------------- OCR fallback for scanned pages ---------------- */

  let ocrWorkerPromise = null;
  async function getOcrWorker() {
    if (!ocrWorkerPromise) ocrWorkerPromise = Tesseract.createWorker('eng', 1, TESS_OPTS);
    return ocrWorkerPromise;
  }
  async function ocrCanvas(canvas) {
    const worker = await getOcrWorker();
    const { data } = await worker.recognize(canvas);
    return data.text || '';
  }

  async function debugExtract(file) {
    const buf = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({ data: buf, password: undefined });
    loadingTask.onPassword = (updatePassword, reason) => {
      const isRetry = reason === pdfjsLib.PasswordResponses.INCORRECT_PASSWORD;
      const pwd = window.prompt(isRetry ? 'That password didn\u2019t work. Try again:' : 'This statement is password protected. Enter its password:');
      if (pwd === null) { loadingTask.destroy(); return; }
      updatePassword(pwd);
    };
    const pdf = await loadingTask.promise;
    const page = await pdf.getPage(1);
    const content = await page.getTextContent();
    const items = content.items.map(it => ({ str: it.str, x: Math.round(it.transform[4]), y: Math.round(it.transform[5]) }));
    const rawJoined = items.map(it => it.str).join('\n');
    const lines = await getLines(page);
    const header = findHeader(lines);
    return {
      itemCount: items.length,
      firstItems: items.slice(0, 40),
      rawTextSample: rawJoined.slice(0, 1500),
      lineCount: lines.length,
      headerFound: !!header,
      headerColumns: header ? header.columns : null,
      firstLinesSample: lines.slice(0, 8).map(l => l.map(it => it.str).join(' | ')),
    };
  }

  /* ---------------- main entry point ---------------- */

  async function parseStatement(file, onStatus) {
    const buf = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({ data: buf, password: undefined });
    loadingTask.onPassword = (updatePassword, reason) => {
      const isRetry = reason === pdfjsLib.PasswordResponses.INCORRECT_PASSWORD;
      const pwd = window.prompt(isRetry ? 'That password didn\u2019t work. Try again:' : 'This statement is password protected. Enter its password:');
      if (pwd === null) { loadingTask.destroy(); return; }
      updatePassword(pwd);
    };
    const pdf = await loadingTask.promise;
    const yearHint = new Date().getFullYear();

    const pageTextContents = [];
    let charCount = 0;
    for (let i = 1; i <= pdf.numPages; i++) {
      onStatus && onStatus(`Reading page ${i} of ${pdf.numPages}…`);
      const page = await pdf.getPage(i);
      const content = await page.getTextContent();
      const pageText = content.items.map(it => it.str).join('\n');
      charCount += pageText.trim().length;
      pageTextContents.push({ page, pageText });
    }

    const avgCharsPerPage = charCount / pdf.numPages;
    const isScanned = avgCharsPerPage < 40;

    if (isScanned) {
      let fullText = '';
      for (let i = 0; i < pageTextContents.length; i++) {
        onStatus && onStatus(`Running on-device OCR, page ${i + 1} of ${pageTextContents.length}…`);
        const { page } = pageTextContents[i];
        const viewport = page.getViewport({ scale: 2.2 });
        const canvas = document.createElement('canvas');
        canvas.width = viewport.width; canvas.height = viewport.height;
        await page.render({ canvasContext: canvas.getContext('2d'), viewport }).promise;
        fullText += (await ocrCanvas(canvas)) + '\n';
      }
      return extractLineCandidates(fullText, yearHint);
    }

    // Try the positional table parser on each page first.
    onStatus && onStatus('Reading transaction table…');
    let candidates = [];
    for (const { page } of pageTextContents) {
      candidates = candidates.concat(await extractTableFromPage(page, yearHint));
    }
    if (candidates.length > 0) return candidates;

    // Fall back to generic line-based parsing.
    const fullText = pageTextContents.map(p => p.pageText).join('\n');
    return extractLineCandidates(fullText, yearHint);
  }

  return { parseStatement, extractLineCandidates, normalizeDate, parseAmount, setDateFormat, getDateFormat, debugExtract };
})();
